
#
# These sources are part of the "C# Programming Series" by Edgar Milvus, 
# you can find it on stores: 
# 
# https://www.amazon.com/dp/B0GKJ3NYL6 or https://tinyurl.com/CSharpProgrammingBooks or 
# https://leanpub.com/u/edgarmilvus (quantity discounts)
# 
# New books info: https://linktr.ee/edgarmilvus 
#
# MIT License
# Copyright (c) 2026 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Source File: solution_exercise_4.cs
# Description: Solution for Exercise 4
# ==========================================

using System;
using System.Collections.Generic;
using System.Linq;

public class FunctionalCosineSimilarity
{
    public static void Main()
    {
        // Sample embeddings (usually generated by AI models)
        double[] vectorA = { 1.0, 2.0, 3.0 };
        double[] vectorB = { 1.0, 2.0, 3.0 }; // Identical to A

        // 1. Calculate Dot Product using Zip
        // Zip merges two sequences by applying a function to corresponding elements.
        double dotProduct = vectorA.Zip(vectorB, (a, b) => a * b).Sum();

        // 2. Calculate Magnitude of A
        double magnitudeA = Math.Sqrt(vectorA.Select(x => x * x).Sum());

        // 3. Calculate Magnitude of B
        double magnitudeB = Math.Sqrt(vectorB.Select(x => x * x).Sum());

        // 4. Compute Similarity
        // Handle division by zero
        double similarity = (magnitudeA == 0 || magnitudeB == 0) 
            ? 0 
            : dotProduct / (magnitudeA * magnitudeB);

        Console.WriteLine($"Cosine Similarity: {similarity:F4}");
    }
}
