
#
# These sources are part of the "C# Programming Series" by Edgar Milvus, 
# you can find it on stores: 
# 
# https://www.amazon.com/dp/B0GKJ3NYL6 or https://tinyurl.com/CSharpProgrammingBooks or 
# https://leanpub.com/u/edgarmilvus (quantity discounts)
# 
# New books info: https://linktr.ee/edgarmilvus 
#
# MIT License
# Copyright (c) 2026 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Source File: basic_basic_code_example.cs
# Description: Basic Code Example
# ==========================================

// ---------------------------------------------------------
// 1. Setup & Imports
// ---------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Pgvector; // Required for the Vector type
using Pgvector.EntityFrameworkCore; // Required for Vector extension methods

// ---------------------------------------------------------
// 2. The Domain Model (The "Smart Fridge" Ingredient)
// ---------------------------------------------------------
public class Ingredient
{
    public int Id { get; set; }
    
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    // This represents the "embedding" or vector representation 
    // of the ingredient (e.g., [Fat, Protein, Sugar, Spiciness])
    // In a real app, this is generated by an AI model.
    public Vector Embedding { get; set; } 
}

// ---------------------------------------------------------
// 3. The Database Context
// ---------------------------------------------------------
public class FridgeContext : DbContext
{
    public DbSet<Ingredient> Ingredients { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // NOTE: In a real app, use ConnectionStrings from configuration.
        // We use an in-memory provider here ONLY for demonstration logic.
        // To use actual pgvector, swap to UseNpgsql with a real connection string.
        optionsBuilder.UseInMemoryDatabase("SmartFridgeDb");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // CRITICAL: Configure the column type for PostgreSQL/pgvector
        // Without this, EF Core might try to map it to a generic byte array or string.
        modelBuilder.Entity<Ingredient>()
            .Property(i => i.Embedding)
            .HasColumnType("vector(4)"); // 4 dimensions for our simple example
    }
}

// ---------------------------------------------------------
// 4. The "Hello World" Logic
// ---------------------------------------------------------
public class Program
{
    public static async Task Main(string[] args)
    {
        // A. Dependency Injection Setup
        var services = new ServiceCollection();
        services.AddDbContext<FridgeContext>();
        var provider = services.BuildServiceProvider();

        // B. Initialize DB and Seed Data
        using (var scope = provider.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<FridgeContext>();
            await context.Database.EnsureCreatedAsync();

            // Seed some data (Vectors: [Fat, Protein, Sugar, Spice])
            // Note: In a real app, these vectors come from AI models (e.g., OpenAI, Azure).
            if (!await context.Ingredients.AnyAsync())
            {
                var items = new[]
                {
                    new Ingredient { Name = "Chicken Breast", Embedding = new Vector(new float[] { 0.1f, 0.9f, 0.0f, 0.0f }) },
                    new Ingredient { Name = "Chocolate Bar",  Embedding = new Vector(new float[] { 0.8f, 0.1f, 0.9f, 0.0f }) },
                    new Ingredient { Name = "Habanero Pepper",Embedding = new Vector(new float[] { 0.0f, 0.1f, 0.0f, 1.0f }) },
                    new Ingredient { Name = "Pork Belly",     Embedding = new Vector(new float[] { 0.9f, 0.2f, 0.0f, 0.0f }) }
                };
                await context.Ingredients.AddRangeAsync(items);
                await context.SaveChangesAsync();
            }
        }

        // C. Perform the Nearest Neighbor Search
        using (var scope = provider.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<FridgeContext>();

            // We are looking for a "Sweet and Fatty" item.
            // Let's define the query vector:
            var queryVector = new Vector(new float[] { 0.85f, 0.1f, 0.85f, 0.0f });

            Console.WriteLine($"Searching for ingredients similar to: [Fat: 0.85, Protein: 0.1, Sugar: 0.85, Spice: 0.0]");

            // THE ANN QUERY:
            // 1. OrderByL2Distance calculates Euclidean distance (lower is better).
            // 2. Take(3) limits the result set.
            // 3. EF Core translates this into SQL: ORDER BY embedding <-> '[0.85,...]' LIMIT 3
            var similarIngredients = await context.Ingredients
                .OrderBy(i => i.Embedding.L2Distance(queryVector))
                .Take(3)
                .ToListAsync();

            Console.WriteLine("\n--- Results ---");
            foreach (var item in similarIngredients)
            {
                // Calculate exact distance for display purposes
                var distance = item.Embedding.L2Distance(queryVector);
                Console.WriteLine($"Found: {item.Name} (Distance: {distance:F4})");
            }
        }
    }
}
