
/*
#
# These sources are part of the "C# Programming Series" by Edgar Milvus, 
# for additional info, new volumes, link to stores:
# https://github.com/edgarmilvus/CSharpProgrammingSeries
#
# MIT License
# Copyright (c) 2026 Edgar Milvus
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
*/

// Source File: basic_basic_code_example.cs
// Description: Basic Code Example
// ==========================================

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

// ---------------------------------------------------------
// REAL-WORLD CONTEXT
// ---------------------------------------------------------
// Imagine you are building a semantic search feature for a 
// corporate knowledge base. Employees can ask questions like 
// "How do I reset my VPN?" or "What is the parental leave policy?".
// Instead of keyword matching, we convert these questions and 
// documents into high-dimensional vectors (embeddings).
// 
// The problem: SQL Server's standard string search cannot compare 
// these mathematical representations efficiently. We need to store 
// these vectors natively and perform similarity searches (e.g., 
// finding the document vector closest to the question vector).
// ---------------------------------------------------------

namespace SqlServerVectorDemo
{
    // ---------------------------------------------------------
    // 1. DOMAIN ENTITY
    // ---------------------------------------------------------
    // Represents a document in our knowledge base.
    public class KnowledgeBaseDocument
    {
        [Key]
        public int Id { get; set; }

        public string Title { get; set; } = string.Empty;

        public string Content { get; set; } = string.Empty;

        // CRITICAL: This property holds the semantic representation 
        // of the content. It is a list of floating-point numbers 
        // generated by an AI model (e.g., text-embedding-ada-002).
        // SQL Server 2022+ supports the 'vector' data type to store this natively.
        [Column(TypeName = "vector(1536)")] // Standard size for many OpenAI embeddings
        public List<float>? Embedding { get; set; }
    }

    // ---------------------------------------------------------
    // 2. DB CONTEXT & CONFIGURATION
    // ---------------------------------------------------------
    public class KnowledgeBaseContext : DbContext
    {
        public DbSet<KnowledgeBaseDocument> Documents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Replace with your actual connection string.
            // Ensure you are targeting SQL Server 2022 or Azure SQL.
            optionsBuilder.UseSqlServer("Server=localhost;Database=VectorDemo;Trusted_Connection=True;TrustServerCertificate=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // We use the Fluent API to configure the vector index.
            // Without an index, searching over high-dimensional vectors is O(N) 
            // and computationally expensive (slow).
            modelBuilder.Entity<KnowledgeBaseDocument>()
                .HasIndex(d => d.Embedding)
                .HasMethod("IVF_FLAT") // Inverted File Index with Flat Compression
                .IsCreatedOnline();    // Allows creation without blocking table access
        }
    }

    // ---------------------------------------------------------
    // 3. SERVICE LAYER (LOGIC)
    // ---------------------------------------------------------
    public class SemanticSearchService
    {
        private readonly KnowledgeBaseContext _context;

        public SemanticSearchService(KnowledgeBaseContext context)
        {
            _context = context;
        }

        // -----------------------------------------------------
        // HELPER: Mock Embedding Generator
        // -----------------------------------------------------
        // In a real app, this calls an AI API (OpenAI, Azure AI).
        // Here, we simulate a 3-dimensional vector for simplicity 
        // (though the config uses 1536 for realism).
        public static List<float> GenerateMockEmbedding(string text)
        {
            // Simulating a vector representation.
            // Hashing the string to generate deterministic "random" floats.
            var hash = text.GetHashCode();
            return new List<float> 
            { 
                Math.Abs(hash % 100) / 100f, 
                Math.Abs(hash * 2 % 100) / 100f, 
                Math.Abs(hash * 3 % 100) / 100f 
            };
        }

        // -----------------------------------------------------
        // OPERATION: Similarity Search (Cosine Distance)
        // -----------------------------------------------------
        // Finds documents semantically closest to the query.
        // We use Euclidean distance (L2) or Cosine Distance. 
        // SQL Server's vector functions handle the math.
        public async Task<List<KnowledgeBaseDocument>> SearchAsync(string query, int topK = 3)
        {
            // 1. Convert query to vector
            var queryEmbedding = GenerateMockEmbedding(query);

            // 2. Execute Vector Search
            // Note: EF Core 8+ supports raw SQL execution, but vector operators 
            // require specific SQL syntax. We use FromSqlRaw for precision here.
            // The 'vector_distance' function calculates the distance between two vectors.
            // We order by ascending distance (closest = smallest distance).
            var sql = @"
                SELECT TOP({0}) 
                    Id, 
                    Title, 
                    Content, 
                    Embedding 
                FROM Documents 
                ORDER BY vector_distance('cosine', Embedding, @p0) ASC";

            // Convert List<float> to a format SQL Server understands: '[1.0, 2.0, 3.0]'
            var vectorLiteral = FormatVectorForSql(queryEmbedding);

            // Execute the query
            var results = await _context.Documents
                .FromSqlRaw(sql, vectorLiteral)
                .AsNoTracking()
                .ToListAsync();

            return results;
        }

        // -----------------------------------------------------
        // HELPER: SQL Vector Formatting
        // -----------------------------------------------------
        // SQL Server expects vector literals in the format: '[v1, v2, v3]'
        private string FormatVectorForSql(List<float> vector)
        {
            if (vector == null || vector.Count == 0) return "[]";
            return "[" + string.Join(", ", vector.Select(v => v.ToString("F6"))) + "]";
        }
    }

    // ---------------------------------------------------------
    // 4. MAIN EXECUTION (HELLO WORLD)
    // ---------------------------------------------------------
    class Program
    {
        static async Task Main(string[] args)
        {
            // Ensure database is created/migrated
            using (var context = new KnowledgeBaseContext())
            {
                await context.Database.EnsureCreatedAsync();

                // Seed Data (if empty)
                if (!context.Documents.Any())
                {
                    var docs = new[]
                    {
                        new KnowledgeBaseDocument 
                        { 
                            Title = "VPN Setup Guide", 
                            Content = "Instructions to configure Cisco AnyConnect.",
                            Embedding = SemanticSearchService.GenerateMockEmbedding("VPN Setup Guide Instructions Cisco AnyConnect")
                        },
                        new KnowledgeBaseDocument 
                        { 
                            Title = "Holiday Calendar", 
                            Content = "List of public holidays for 2024.",
                            Embedding = SemanticSearchService.GenerateMockEmbedding("Holiday Calendar Public Holidays 2024")
                        },
                        new KnowledgeBaseDocument 
                        { 
                            Title = "Expense Policy", 
                            Content = "How to submit travel expenses.",
                            Embedding = SemanticSearchService.GenerateMockEmbedding("Expense Policy Travel Submit Reimbursement")
                        }
                    };
                    context.Documents.AddRange(docs);
                    await context.SaveChangesAsync();
                }
            }

            // Perform Search
            using (var context = new KnowledgeBaseContext())
            {
                var service = new SemanticSearchService(context);
                
                // We search for "travel costs", which semantically relates to "Expense Policy"
                // but does not contain the keyword "expense".
                string userQuery = "How do I claim money for flights?";
                
                Console.WriteLine($"Query: \"{userQuery}\"\n");
                
                var results = await service.SearchAsync(userQuery);

                Console.WriteLine("Semantic Search Results:");
                foreach (var doc in results)
                {
                    Console.WriteLine($" - {doc.Title} (Relevance Score: N/A in this demo)");
                }
            }
        }
    }
}
